/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project2.pkg;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author heyitstasyaa
 */
public class Frame extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();
    Dashboard dash;
    DataBarang barang;
    BarangMasuk masuk;
    public Frame() {
        initComponents();
        dash = new Dashboard();
        barang = new DataBarang();
        main.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        main. add(dash, c);
        main.add(barang,c);
        dash.setVisible(true);
        barang.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        DataBarang = new javax.swing.JPanel();
        lblDataBarang = new javax.swing.JLabel();
        BarangMasuk = new javax.swing.JPanel();
        lblBarangMasuk = new javax.swing.JLabel();
        BarangKeluar = new javax.swing.JPanel();
        lblBarangKeluar = new javax.swing.JLabel();
        Pesanan = new javax.swing.JPanel();
        lblPesanan = new javax.swing.JLabel();
        Laporan = new javax.swing.JPanel();
        lblLaporan = new javax.swing.JLabel();
        main = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBackground(new java.awt.Color(58, 56, 62));
        topPanel.setPreferredSize(new java.awt.Dimension(1366, 73));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        sidePanel.setBackground(new java.awt.Color(205, 204, 206));
        sidePanel.setPreferredSize(new java.awt.Dimension(240, 768));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setBackground(new java.awt.Color(205, 204, 206));
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardMouseExited(evt);
            }
        });

        lblDashboard.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/grid.png"))); // NOI18N
        lblDashboard.setText("DASHBOARD");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 40));

        DataBarang.setBackground(new java.awt.Color(205, 204, 206));
        DataBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataBarangMouseExited(evt);
            }
        });

        lblDataBarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblDataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/package.png"))); // NOI18N
        lblDataBarang.setText("DATA BARANG");

        javax.swing.GroupLayout DataBarangLayout = new javax.swing.GroupLayout(DataBarang);
        DataBarang.setLayout(DataBarangLayout);
        DataBarangLayout.setHorizontalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        DataBarangLayout.setVerticalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDataBarang)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(DataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        BarangMasuk.setBackground(new java.awt.Color(205, 204, 206));
        BarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangMasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BarangMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BarangMasukMouseExited(evt);
            }
        });

        lblBarangMasuk.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblBarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/corner-right-down.png"))); // NOI18N
        lblBarangMasuk.setText("BARANG MASUK");

        javax.swing.GroupLayout BarangMasukLayout = new javax.swing.GroupLayout(BarangMasuk);
        BarangMasuk.setLayout(BarangMasukLayout);
        BarangMasukLayout.setHorizontalGroup(
            BarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangMasukLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        BarangMasukLayout.setVerticalGroup(
            BarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBarangMasuk)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(BarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 40));

        BarangKeluar.setBackground(new java.awt.Color(205, 204, 206));
        BarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BarangKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BarangKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BarangKeluarMouseExited(evt);
            }
        });

        lblBarangKeluar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblBarangKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/corner-right-up.png"))); // NOI18N
        lblBarangKeluar.setText("BARANG KELUAR");

        javax.swing.GroupLayout BarangKeluarLayout = new javax.swing.GroupLayout(BarangKeluar);
        BarangKeluar.setLayout(BarangKeluarLayout);
        BarangKeluarLayout.setHorizontalGroup(
            BarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangKeluarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        BarangKeluarLayout.setVerticalGroup(
            BarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBarangKeluar)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(BarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 40));

        Pesanan.setBackground(new java.awt.Color(205, 204, 206));
        Pesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PesananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PesananMouseExited(evt);
            }
        });

        lblPesanan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/transaction-order.png"))); // NOI18N
        lblPesanan.setText("PESANAN");

        javax.swing.GroupLayout PesananLayout = new javax.swing.GroupLayout(Pesanan);
        Pesanan.setLayout(PesananLayout);
        PesananLayout.setHorizontalGroup(
            PesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesananLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        PesananLayout.setVerticalGroup(
            PesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPesanan)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(Pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 40));

        Laporan.setBackground(new java.awt.Color(205, 204, 206));

        lblLaporan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/file-text.png"))); // NOI18N
        lblLaporan.setText("LAPORAN");

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLaporan)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        sidePanel.add(Laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        getContentPane().add(sidePanel, java.awt.BorderLayout.LINE_START);

        main.setPreferredSize(new java.awt.Dimension(1126, 699));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1126, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        dash.setVisible(true);
        barang.setVisible(false);
    }//GEN-LAST:event_DashboardMouseClicked

    private void DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseEntered
        Dashboard.setBackground(new Color(242,242,242));
        Dashboard.setOpaque(true);
    }//GEN-LAST:event_DashboardMouseEntered

    private void DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseExited
        Dashboard.setBackground(new Color(205,204,206));
    }//GEN-LAST:event_DashboardMouseExited

    private void DataBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMouseClicked
        dash.setVisible(false);
        barang.setVisible(true);
    }//GEN-LAST:event_DataBarangMouseClicked

    private void DataBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMouseEntered
        DataBarang.setBackground(new Color(242,242,242));
        DataBarang.setOpaque(true);
    }//GEN-LAST:event_DataBarangMouseEntered

    private void DataBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataBarangMouseExited
        DataBarang.setBackground(new Color(205,204,206));
    }//GEN-LAST:event_DataBarangMouseExited

    private void BarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMasukMouseClicked
        dash.setVisible(false);
        barang.setVisible(false);
        masuk.setVisible(true);
//        keluar.setVisible(false);
//        pesan.setVisible(false);
//        laporan.setVisible(false);
        
    }//GEN-LAST:event_BarangMasukMouseClicked

    private void BarangMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMasukMouseEntered
        BarangMasuk.setBackground(new Color(242,242,242));
        BarangMasuk.setOpaque(true);
    }//GEN-LAST:event_BarangMasukMouseEntered

    private void BarangMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangMasukMouseExited
        BarangMasuk.setBackground(new Color(205,204,206));
    }//GEN-LAST:event_BarangMasukMouseExited

    private void BarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BarangKeluarMouseClicked

    private void BarangKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangKeluarMouseEntered
        BarangKeluar.setBackground(new Color(242,242,242));
        BarangKeluar.setOpaque(true);
    }//GEN-LAST:event_BarangKeluarMouseEntered

    private void BarangKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarangKeluarMouseExited
        BarangKeluar.setBackground(new Color(205,204,206));
    }//GEN-LAST:event_BarangKeluarMouseExited

    private void PesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PesananMouseClicked

    private void PesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PesananMouseEntered

    private void PesananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PesananMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PesananMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarangKeluar;
    private javax.swing.JPanel BarangMasuk;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel DataBarang;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Pesanan;
    private javax.swing.JLabel lblBarangKeluar;
    private javax.swing.JLabel lblBarangMasuk;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDataBarang;
    private javax.swing.JLabel lblLaporan;
    private javax.swing.JLabel lblPesanan;
    private javax.swing.JLayeredPane main;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
