/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project2.pkg;

import Connection.pkg.Connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author heyitstasyaa
 */
public class InsertDB extends javax.swing.JFrame {

    /**
     * Creates new form InsertDataBarang
     */
    public InsertDB() {
        initComponents();
        autoIdBarang();
        txtNamaBarang.requestFocus();
        
        BtnSave.setBackground(new Color(0,0,0));
        BtnSave.setBorder(null);
        
        BtnCancel.setBackground(new Color(0,0,0));
        BtnCancel.setBorder(null);
        
    }

    private void autoIdBarang() {
        String Id = "B0000";
        int i = 0;
        try {
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.Statement stat = conn.createStatement();
            String sql = "SELECT IdBarang FROM databarang";
            ResultSet rs = stat.executeQuery(sql);
            while (rs.next()) {
                Id = rs.getString("IdBarang");
            }
            Id = Id.substring(1);
            i = Integer.parseInt(Id)+1;
            Id = "000" + i;
            Id = "B" + Id.substring(Id.length()-3);
            txtIdBarang.setText(Id);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSatuan = new javax.swing.JTextField();
        txtJumlahStok = new javax.swing.JTextField();
        txtJenisBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtIdBarang = new javax.swing.JTextField();
        BtnCancel = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSatuan.setBackground(new java.awt.Color(217, 217, 217));
        txtSatuan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtSatuan.setBorder(null);
        getContentPane().add(txtSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 330, 35));

        txtJumlahStok.setBackground(new java.awt.Color(217, 217, 217));
        txtJumlahStok.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtJumlahStok.setBorder(null);
        getContentPane().add(txtJumlahStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 330, 35));

        txtJenisBarang.setBackground(new java.awt.Color(217, 217, 217));
        txtJenisBarang.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtJenisBarang.setBorder(null);
        getContentPane().add(txtJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 330, 35));

        txtNamaBarang.setBackground(new java.awt.Color(217, 217, 217));
        txtNamaBarang.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNamaBarang.setBorder(null);
        getContentPane().add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 330, 35));

        txtIdBarang.setBackground(new java.awt.Color(217, 217, 217));
        txtIdBarang.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtIdBarang.setBorder(null);
        getContentPane().add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 330, 35));

        BtnCancel.setBackground(new java.awt.Color(0, 0, 51));
        BtnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 120, 40));

        BtnSave.setBackground(new java.awt.Color(0, 0, 51));
        BtnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnSave.setForeground(new java.awt.Color(225, 225, 225));
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/Insert DB.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        try {
            String sql = "INSERT INTO databarang VALUES ('" + txtIdBarang.getText() + "','"
            + txtNamaBarang.getText() + "','" + txtJenisBarang.getText() + "','"
            + txtJumlahStok.getText() + "','" + txtSatuan.getText() + "')"; 
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        setVisible(false);
        new DataBarang().setVisible(true);
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtJenisBarang;
    private javax.swing.JTextField txtJumlahStok;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables
}
