/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project2.pkg;

import Connection.pkg.Connect;
import Connection.pkg.Sessions;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author heyitstasyaa
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        HidePass.setVisible(false);
        BtnLogin.setBackground(new Color(0,0,0));
        BtnLogin.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForgot = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        ShowPass = new javax.swing.JLabel();
        HidePass = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotMouseClicked(evt);
            }
        });
        getContentPane().add(lblForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 367, 65, 25));

        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 290, 30));

        ShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/eye.png"))); // NOI18N
        ShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPassMouseClicked(evt);
            }
        });
        getContentPane().add(ShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 399, 30, 50));

        HidePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/eye-off.png"))); // NOI18N
        HidePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HidePassMouseClicked(evt);
            }
        });
        getContentPane().add(HidePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 399, 30, 50));

        BtnLogin.setBackground(new java.awt.Color(0, 0, 51));
        BtnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Login");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 508, 180, 60));

        txtUsername.setBackground(new java.awt.Color(238, 238, 241));
        txtUsername.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtUsername.setToolTipText("");
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 275, 330, 40));

        txtPassword.setBackground(new java.awt.Color(238, 238, 241));
        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 404, 290, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pkg/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        try {
            String sql = "SELECT * FROM akun WHERE username ='" + txtUsername.getText() +
            "'AND password ='" + txtPassword.getText() + "'";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String usname = rs.getString("username");
                String pass = rs.getString("password");
                String user = rs.getString("user");

                if (usname.equals(usname) && pass.equals(pass)) {
                    if(user.equals("Admin")) {
                        Sessions.setName(rs.getString("name"));
                        setVisible(false);
                        new Frame().setVisible(true);
                    } else if (user.equals("Karyawan")) {
                        Sessions.setName(rs.getString("name"));
                        setVisible(false);
                        new Frame().setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null,"Username atau Password salah");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        this.setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void lblForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseClicked
        this.setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_lblForgotMouseClicked

    private void ShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPassMouseClicked
        ShowPass.setVisible(false);
        HidePass.setVisible(true);
        txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_ShowPassMouseClicked

    private void HidePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidePassMouseClicked
        ShowPass.setVisible(true);
        HidePass.setVisible(false);
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_HidePassMouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        try {
            String sql = "SELECT * FROM akun WHERE Id ='" + txtUsername.getText() + "'";
            java.sql.Connection conn = (Connection) Connect.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                String usname = rs.getString("Id");
                String user = rs.getString("user");

                if (usname.equals(usname)) {
                    if(user.equals("Admin")) {
                        Sessions.setName(rs.getString("name"));
                        setVisible(false);
                        new Frame().setVisible(true);
                    } else if (user.equals("Karyawan")) {
                        Sessions.setName(rs.getString("name"));
                        setVisible(false);
                        new Frame().setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null,"Kart26670u belum terdaftar !");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel HidePass;
    private javax.swing.JLabel ShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
